feat: Upgrade Docker Compose for EdgeX services to 3.1
intel/AiCSD pull request #66
Opened 2023-12-15 16:08 UTC by ejlee3

Closes: #44

## PR Checklist

## Author Mandatory (to be filled by PR Author/Submitter)

### CODE MAINTAINABILITY

- [x] **_Commit Message meets guidelines as indicated in the URL\*_**
    - <https://github.com/intel/AiCSD/blob/main/.github/CONTRIBUTING.md>
- [ ] Tests for the changes have been added (required for bug fixes / features). **If not, state why not**
- [ ] Added labels (these are git labels such as bug or enhancement)
- [ ] For any API changes or service changes, updates to the documentation were made (Swagger APIs & GitHub Docs). **If not, state why not**
- [x] **_Every commit is a single defect fix and does not mix feature addition or changes\*_**

### What are the steps to test this PR contribution?

How does a reviewer know it works?
run `docker compose -p edgex -f docker-compose-edgex.yml  up -d`
verify all containers come up successfully

Are there any special instructions beyond standard workflow?

## Maintainer Mandatory (to be filled by PR Reviewer/Approving Maintainer)

### QUALITY CHECKS

- [ ] **_Quality of code (At least one should be checked as applicable)\*_**
    - [ ] Commit Message meets guidelines
    - [ ] Code copyright is correct
    - [ ] PR changes adhere to industry practices and standards as well as domain or language specific anti-patterns
    - [ ] Adopted domain specific coding standards ([Go Coding Standards](https://go.dev/doc/effective_go))
    - [ ] Code is adequately commented and documented
    - [ ] Confusing logic is explained in comments
    - [ ] Error and exception code paths implemented correctly
    - [ ] Tracing output are minimized and logic
- [ ] **_Test coverage shows adequate coverage with required CI functional tests pass on all supported platforms\*_**
- [ ] **_Static code scan report shows zero critical issues\*_**

## Other information

2024-01-08 17:34 UTC, lenny-intel requested changes

2024-01-08 17:34 UTC, lenny-intel commented on docker-compose-edgex.yml
> +          - edgex-kong
This should be able to be removed. Bryon thinks it was the edgex UI that was needing it. I am looking at removing it in this next release.

2024-01-08 17:34 UTC, lenny-intel commented on docker-compose-edgex.yml
> +    container_name: edgex-security-bootstrapper
Remove?

2024-01-08 23:08 UTC, ejlee3 commented on docker-compose-edgex.yml
> +    container_name: edgex-core-consul
ah I did it this way because I was lazy. If we want to remove container name, we need to change all the container headers (ie line 11 here - from `consul` to `edgex-core-consul`)

2024-01-08 23:08 UTC, ejlee3 commented on docker-compose-edgex.yml
> +    container_name: edgex-core-consul
same applies to all container name changes.

2024-01-08 23:09 UTC, ejlee3 commented on docker-compose-edgex.yml
> +  database:
we can - it depends on how we want to reference it here. I think in EdgeX 3.1 we use database, but I can change them all if we prefer.

2024-01-08 23:13 UTC, lenny-intel commented on docker-compose-edgex.yml
> +  database:
It has always been `database` in edgex. Someone decided it was better as `edgex-redis` for KP.

2024-01-08 23:15 UTC, lenny-intel commented on docker-compose-edgex.yml
> +    container_name: edgex-core-consul
I think it was Antonio that made that change for some reason. Please check with him.

2024-01-09 23:35 UTC, lenny-intel requested changes

2024-01-09 23:35 UTC, lenny-intel commented on edgex-res/common-config-bootstrapper-configuration.yaml
> +all-services:
Why is this file needed when you can use env overrides to tweak values.

2024-01-09 23:41 UTC, ejlee3 commented on edgex-res/common-config-bootstrapper-configuration.yaml
> +all-services:
can we use env overrides to remove settings? We need to remove the clients for app services

2024-01-09 23:44 UTC, lenny-intel commented on edgex-res/common-config-bootstrapper-configuration.yaml
> +all-services:
Ahh, ok. Make sense.

2024-01-09 23:54 UTC, lenny-intel approved these changes
LGTM

2024-01-10 17:21 UTC, merged