feat: Update gateway and oem compose files for EdgeX 3.1
intel/AiCSD pull request #67
Opened 2023-12-18 21:40 UTC by ejlee3

Closes: #45

## PR Checklist

## Author Mandatory (to be filled by PR Author/Submitter)

### CODE MAINTAINABILITY

- [x] **_Commit Message meets guidelines as indicated in the URL\*_**
    - <https://github.com/intel/AiCSD/blob/main/.github/CONTRIBUTING.md>
- [ ] Tests for the changes have been added (required for bug fixes / features). **If not, state why not** - needs service updates first
- [ ] Added labels (these are git labels such as bug or enhancement)
- [ ] For any API changes or service changes, updates to the documentation were made (Swagger APIs & GitHub Docs). **If not, state why not**
- [x] **_Every commit is a single defect fix and does not mix feature addition or changes\*_**

### What are the steps to test this PR contribution?

How does a reviewer know it works?

Are there any special instructions beyond standard workflow?

## Maintainer Mandatory (to be filled by PR Reviewer/Approving Maintainer)

### QUALITY CHECKS

- [ ] **_Quality of code (At least one should be checked as applicable)\*_**
    - [ ] Commit Message meets guidelines
    - [ ] Code copyright is correct
    - [ ] PR changes adhere to industry practices and standards as well as domain or language specific anti-patterns
    - [ ] Adopted domain specific coding standards ([Go Coding Standards](https://go.dev/doc/effective_go))
    - [ ] Code is adequately commented and documented
    - [ ] Confusing logic is explained in comments
    - [ ] Error and exception code paths implemented correctly
    - [ ] Tracing output are minimized and logic
- [ ] **_Test coverage shows adequate coverage with required CI functional tests pass on all supported platforms\*_**
- [ ] **_Static code scan report shows zero critical issues\*_**

## Other information

2024-01-08 17:41 UTC, lenny-intel requested changes
I reviewed the first file. Will continue one question answered.

2024-01-08 17:41 UTC, lenny-intel commented on docker-compose-gateway.yml
>        MESSAGEQUEUE_HOST: edgex-redis
Remove. Name has been changed to MESSAGEBUS_HOST and is now in common config
Same for other services.

2024-01-08 17:41 UTC, lenny-intel commented on docker-compose-gateway.yml
>        TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
Remove. Names have changed and now in common config
Same for other services.

2024-01-08 17:41 UTC, lenny-intel commented on docker-compose-gateway.yml
> -      EDGEX_SECURITY_SECRET_STORE: "true"
Why is this removed? Is this not the secure mode version?

2024-01-08 23:13 UTC, ejlee3 commented on docker-compose-gateway.yml
> -      EDGEX_SECURITY_SECRET_STORE: "true"
we aren't using Kong anymore...correct?

2024-01-08 23:14 UTC, ejlee3 commented on docker-compose-gateway.yml
>        TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
which setting do we want to remove here?

2024-01-09 15:56 UTC, lenny-intel requested changes

2024-01-09 15:56 UTC, lenny-intel commented on docker-compose-gateway.yml
>        WRITABLE_LOGLEVEL: DEBUG
Do we really want DEBUG on all the time?

2024-01-09 15:56 UTC, lenny-intel commented on docker-compose-gateway.yml
>        REGISTRY_HOST: edgex-core-consul
remove REGISTRY_HOST since it is part of common config. Here and on other services in all compose files

2024-01-09 15:56 UTC, lenny-intel commented on docker-compose-gateway.yml
>        PROXY_SETUP_HOST: edgex-security-proxy-setup
Remove PROXY_SETUP_HOST here and other KP services
It is used in proxy_setup_wait_install.sh and nginx_wait_install.sh entry point scripts which are not used by this services in all compose files

2024-01-09 15:56 UTC, lenny-intel commented on docker-compose-oem-standalone.yml
> +      STAGEGATE_WAITFOR_TIMEOUT: 60s
The STAGEGATE_*  envs are only used for the security entrypoint scripts which this service does specify an entrypoint. 
Same with the SPIFFE_* envs.
Not sure how this was working...

2024-01-09 17:17 UTC, lenny-intel commented on docker-compose-oem.yml
>        SPIFFE_TRUSTDOMAIN: edgexfoundry.org
Remove 
```suggestion

```

2024-01-09 17:17 UTC, lenny-intel commented on docker-compose-oem.yml
> +      - consul
hi

2024-01-09 17:22 UTC, ejlee3 commented on docker-compose-sim.yml
>        SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
remove SPIFFE variables, add back STAGEGATE ones

2024-01-09 17:22 UTC, ejlee3 commented on docker-compose-pipeline-val.yml
>        SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
remove `SPIFFE` variables, add `STAGEGATE` ones

2024-01-09 19:20 UTC, ejlee3 commented on docker-compose-gateway.yml
>        WRITABLE_LOGLEVEL: DEBUG
the 'DEBUG' logs do give a nice amount of info from our custom services, but we can turn it off if we decide to.

2024-01-09 23:39 UTC, lenny-intel requested changes

2024-01-09 23:39 UTC, lenny-intel commented on docker-compose-pipeline-val.yml
>        TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
```suggestion

```

2024-01-10 17:04 UTC, lenny-intel approved these changes
LGTM

2024-01-10 17:21 UTC, merged